var g_moduleList = [
  "tango.core.Array", "tango.core.ArrayLiteral", "tango.core.BitArray",
  "tango.core.BitManip", "tango.core.ByteSwap", "tango.core.Exception",
  "tango.core.Memory", "tango.core.Octal", "tango.core.Runtime",
  "tango.core.RuntimeTraits", "tango.core.Signal", "tango.core.Thread",
  "tango.core.ThreadPool", "tango.core.Time", "tango.core.Traits",
  "tango.core.Tuple", "tango.core.Vararg", "tango.core.Variant",
  "tango.core.Version", "tango.core.sync.Atomic", "tango.core.sync.Barrier",
  "tango.core.sync.Condition", "tango.core.sync.Config",
  "tango.core.sync.Mutex", "tango.core.sync.ReadWriteMutex",
  "tango.core.sync.Semaphore", "tango.core.tools.Cpuid",
  "tango.core.tools.Demangler", "tango.core.tools.FrameInfo",
  "tango.core.tools.LinuxStackTrace", "tango.core.tools.StackTrace",
  "tango.core.tools.TraceExceptions", "tango.core.tools.WinStackTrace",
  "tango.core.util.console", "tango.core.util.string", "tango.io.Console",
  "tango.io.FilePath", "tango.io.FileScan", "tango.io.FileSystem",
  "tango.io.Path", "tango.io.Stdout", "tango.io.UnicodeFile",
  "tango.io.device.Array", "tango.io.device.BitBucket",
  "tango.io.device.Conduit", "tango.io.device.Device", "tango.io.device.File",
  "tango.io.device.FileMap", "tango.io.device.SerialPort",
  "tango.io.device.TempFile", "tango.io.device.ThreadPipe",
  "tango.io.model.IConduit", "tango.io.model.IFile",
  "tango.io.selector.AbstractSelector", "tango.io.selector.EpollSelector",
  "tango.io.selector.PollSelector", "tango.io.selector.SelectSelector",
  "tango.io.selector.Selector", "tango.io.selector.SelectorException",
  "tango.io.selector.model.ISelector", "tango.io.stream.Buffered",
  "tango.io.stream.Bzip", "tango.io.stream.Data", "tango.io.stream.DataFile",
  "tango.io.stream.Delimiters", "tango.io.stream.Digester",
  "tango.io.stream.Endian", "tango.io.stream.Format", "tango.io.stream.Greedy",
  "tango.io.stream.Iterator", "tango.io.stream.Lines", "tango.io.stream.Map",
  "tango.io.stream.Patterns", "tango.io.stream.Quotes",
  "tango.io.stream.Snoop", "tango.io.stream.Text", "tango.io.stream.TextFile",
  "tango.io.stream.Typed", "tango.io.stream.Utf", "tango.io.stream.Zlib",
  "tango.io.vfs.FileFolder", "tango.io.vfs.FtpFolder",
  "tango.io.vfs.LinkedFolder", "tango.io.vfs.VirtualFolder",
  "tango.io.vfs.ZipFolder", "tango.io.vfs.model.Vfs", "tango.math.Bessel",
  "tango.math.BigInt", "tango.math.Bracket", "tango.math.Elliptic",
  "tango.math.ErrorFunction", "tango.math.GammaFunction", "tango.math.IEEE",
  "tango.math.Math", "tango.math.Probability", "tango.math.random.ExpSource",
  "tango.math.random.Kiss", "tango.math.random.NormalSource",
  "tango.math.random.Random", "tango.math.random.Twister",
  "tango.math.random.Ziggurat", "tango.math.random.engines.ArraySource",
  "tango.math.random.engines.CMWC", "tango.math.random.engines.KISS",
  "tango.math.random.engines.KissCmwc", "tango.math.random.engines.Sync",
  "tango.math.random.engines.Twister", "tango.math.random.engines.URandom",
  "tango.net.InternetAddress", "tango.net.Uri", "tango.net.device.Berkeley",
  "tango.net.device.Datagram", "tango.net.device.LocalSocket",
  "tango.net.device.Multicast", "tango.net.device.SSLSocket",
  "tango.net.device.Socket", "tango.net.ftp.FtpClient", "tango.net.ftp.Telnet",
  "tango.net.http.ChunkStream", "tango.net.http.HttpClient",
  "tango.net.http.HttpConst", "tango.net.http.HttpCookies",
  "tango.net.http.HttpGet", "tango.net.http.HttpHeaders",
  "tango.net.http.HttpParams", "tango.net.http.HttpPost",
  "tango.net.http.HttpStack", "tango.net.http.HttpTokens",
  "tango.net.http.HttpTriplet", "tango.net.http.model.HttpParamsView",
  "tango.net.model.UriView", "tango.net.util.MemCache", "tango.net.util.PKI",
  "tango.net.util.c.OpenSSL", "tango.stdc.complex", "tango.stdc.config",
  "tango.stdc.ctype", "tango.stdc.errno", "tango.stdc.fenv",
  "tango.stdc.inttypes", "tango.stdc.limits", "tango.stdc.locale",
  "tango.stdc.math", "tango.stdc.posix.arpa.inet", "tango.stdc.posix.config",
  "tango.stdc.posix.dirent", "tango.stdc.posix.dlfcn",
  "tango.stdc.posix.fcntl", "tango.stdc.posix.grp",
  "tango.stdc.posix.inttypes", "tango.stdc.posix.langinfo",
  "tango.stdc.posix.net.if_", "tango.stdc.posix.netinet.in_",
  "tango.stdc.posix.netinet.tcp", "tango.stdc.posix.poll",
  "tango.stdc.posix.pthread", "tango.stdc.posix.pwd", "tango.stdc.posix.sched",
  "tango.stdc.posix.semaphore", "tango.stdc.posix.setjmp",
  "tango.stdc.posix.signal", "tango.stdc.posix.stdio",
  "tango.stdc.posix.stdlib", "tango.stdc.posix.sys.ipc",
  "tango.stdc.posix.sys.mman", "tango.stdc.posix.sys.select",
  "tango.stdc.posix.sys.shm", "tango.stdc.posix.sys.socket",
  "tango.stdc.posix.sys.stat", "tango.stdc.posix.sys.statvfs",
  "tango.stdc.posix.sys.time", "tango.stdc.posix.sys.types",
  "tango.stdc.posix.sys.uio", "tango.stdc.posix.sys.utsname",
  "tango.stdc.posix.sys.wait", "tango.stdc.posix.termios",
  "tango.stdc.posix.time", "tango.stdc.posix.ucontext",
  "tango.stdc.posix.unistd", "tango.stdc.posix.utime", "tango.stdc.signal",
  "tango.stdc.stdarg", "tango.stdc.stddef", "tango.stdc.stdint",
  "tango.stdc.stdio", "tango.stdc.stdlib", "tango.stdc.string",
  "tango.stdc.stringz", "tango.stdc.tgmath", "tango.stdc.time",
  "tango.stdc.wctype", "tango.sys.Common", "tango.sys.Environment",
  "tango.sys.HomeFolder", "tango.sys.Pipe", "tango.sys.Process",
  "tango.sys.SharedLib", "tango.sys.consts.errno", "tango.sys.consts.fcntl",
  "tango.sys.consts.socket", "tango.sys.consts.sysctl",
  "tango.sys.consts.unistd", "tango.sys.darwin.consts.errno",
  "tango.sys.darwin.consts.fcntl", "tango.sys.darwin.consts.machine",
  "tango.sys.darwin.consts.socket", "tango.sys.darwin.consts.sysctl",
  "tango.sys.darwin.consts.unistd", "tango.sys.darwin.darwin",
  "tango.sys.freebsd.consts.errno", "tango.sys.freebsd.consts.fcntl",
  "tango.sys.freebsd.consts.socket", "tango.sys.freebsd.consts.sysctl",
  "tango.sys.freebsd.consts.unistd", "tango.sys.freebsd.freebsd",
  "tango.sys.linux.consts.errno", "tango.sys.linux.consts.fcntl",
  "tango.sys.linux.consts.socket", "tango.sys.linux.consts.sysctl",
  "tango.sys.linux.consts.unistd", "tango.sys.linux.epoll",
  "tango.sys.linux.inotify", "tango.sys.linux.linux", "tango.sys.linux.tipc",
  "tango.sys.solaris.consts.errno", "tango.sys.solaris.consts.fcntl",
  "tango.sys.solaris.consts.socket", "tango.sys.solaris.consts.sysctl",
  "tango.sys.solaris.consts.unistd", "tango.sys.solaris.solaris",
  "tango.sys.win32.CodePage", "tango.sys.win32.IUnknown",
  "tango.sys.win32.Macros", "tango.sys.win32.Process",
  "tango.sys.win32.SpecialPath", "tango.sys.win32.Types",
  "tango.sys.win32.UserGdi", "tango.sys.win32.WsaSock",
  "tango.sys.win32.consts.errno", "tango.sys.win32.consts.fcntl",
  "tango.sys.win32.consts.socket", "tango.sys.win32.consts.sysctl",
  "tango.sys.win32.consts.unistd", "tango.text.Arguments", "tango.text.Ascii",
  "tango.text.Regex", "tango.text.Search", "tango.text.Text",
  "tango.text.Unicode", "tango.text.UnicodeData", "tango.text.Util",
  "tango.text.convert.DateTime", "tango.text.convert.Float",
  "tango.text.convert.Format", "tango.text.convert.Integer",
  "tango.text.convert.Layout", "tango.text.convert.TimeStamp",
  "tango.text.convert.UnicodeBom", "tango.text.convert.Utf",
  "tango.text.json.Json", "tango.text.json.JsonEscape",
  "tango.text.json.JsonParser", "tango.text.locale.Collation",
  "tango.text.locale.Convert", "tango.text.locale.Core",
  "tango.text.locale.Data", "tango.text.locale.Locale",
  "tango.text.locale.Parse", "tango.text.locale.Posix",
  "tango.text.locale.Win32", "tango.text.xml.DocEntity",
  "tango.text.xml.DocPrinter", "tango.text.xml.DocTester",
  "tango.text.xml.Document", "tango.text.xml.PullParser",
  "tango.text.xml.SaxParser", "tango.time.Clock", "tango.time.ISO8601",
  "tango.time.StopWatch", "tango.time.Time", "tango.time.WallClock",
  "tango.time.chrono.Calendar", "tango.time.chrono.Gregorian",
  "tango.time.chrono.GregorianBased", "tango.time.chrono.Hebrew",
  "tango.time.chrono.Hijri", "tango.time.chrono.Japanese",
  "tango.time.chrono.Korean", "tango.time.chrono.Taiwan",
  "tango.time.chrono.ThaiBuddhist", "tango.util.Convert", "tango.util.MinMax",
  "tango.util.cipher.AES", "tango.util.cipher.Blowfish",
  "tango.util.cipher.ChaCha", "tango.util.cipher.Cipher",
  "tango.util.cipher.RC4", "tango.util.cipher.RC6",
  "tango.util.cipher.Salsa20", "tango.util.cipher.TEA",
  "tango.util.cipher.XTEA", "tango.util.compress.Zip",
  "tango.util.compress.c.bzlib", "tango.util.compress.c.zlib",
  "tango.util.container.CircularList", "tango.util.container.Clink",
  "tango.util.container.Container", "tango.util.container.HashMap",
  "tango.util.container.HashSet", "tango.util.container.LinkedList",
  "tango.util.container.RedBlack", "tango.util.container.Slink",
  "tango.util.container.SortedMap", "tango.util.container.model.IContainer",
  "tango.util.container.more.BitSet", "tango.util.container.more.CacheMap",
  "tango.util.container.more.HashFile", "tango.util.container.more.Heap",
  "tango.util.container.more.Stack", "tango.util.container.more.StackMap",
  "tango.util.container.more.Vector", "tango.util.digest.Crc32",
  "tango.util.digest.Digest", "tango.util.digest.Md2", "tango.util.digest.Md4",
  "tango.util.digest.Md5", "tango.util.digest.MerkleDamgard",
  "tango.util.digest.Ripemd128", "tango.util.digest.Ripemd160",
  "tango.util.digest.Ripemd256", "tango.util.digest.Ripemd320",
  "tango.util.digest.Sha0", "tango.util.digest.Sha01",
  "tango.util.digest.Sha1", "tango.util.digest.Sha256",
  "tango.util.digest.Sha512", "tango.util.digest.Tiger",
  "tango.util.digest.Whirlpool", "tango.util.encode.Base16",
  "tango.util.encode.Base32", "tango.util.encode.Base64",
  "tango.util.log.AppendConsole", "tango.util.log.AppendFile",
  "tango.util.log.AppendFiles", "tango.util.log.AppendMail",
  "tango.util.log.AppendSocket", "tango.util.log.AppendSyslog",
  "tango.util.log.Config", "tango.util.log.ConfigProps",
  "tango.util.log.LayoutChainsaw", "tango.util.log.LayoutDate",
  "tango.util.log.Log", "tango.util.log.Trace", "tango.util.log.model.ILogger",
  "tango.util.uuid.NamespaceGenV3", "tango.util.uuid.NamespaceGenV5",
  "tango.util.uuid.RandomGen", "tango.util.uuid.Uuid",
];

var g_packageTree = new PackageTree(P('', [
  P('tango',[
    P('tango.core',[
      P('tango.core.sync',[
        M('tango.core.sync.Atomic'),
        M('tango.core.sync.Barrier'),
        M('tango.core.sync.Condition'),
        M('tango.core.sync.Config'),
        M('tango.core.sync.Mutex'),
        M('tango.core.sync.ReadWriteMutex'),
        M('tango.core.sync.Semaphore'),
      ]),
      P('tango.core.tools',[
        M('tango.core.tools.Cpuid'),
        M('tango.core.tools.Demangler'),
        M('tango.core.tools.FrameInfo'),
        M('tango.core.tools.LinuxStackTrace'),
        M('tango.core.tools.StackTrace'),
        M('tango.core.tools.TraceExceptions'),
        M('tango.core.tools.WinStackTrace'),
      ]),
      P('tango.core.util',[
        M('tango.core.util.console'),
        M('tango.core.util.string'),
      ]),
      M('tango.core.Array'),
      M('tango.core.ArrayLiteral'),
      M('tango.core.BitArray'),
      M('tango.core.BitManip'),
      M('tango.core.ByteSwap'),
      M('tango.core.Exception'),
      M('tango.core.Memory'),
      M('tango.core.Octal'),
      M('tango.core.Runtime'),
      M('tango.core.RuntimeTraits'),
      M('tango.core.Signal'),
      M('tango.core.Thread'),
      M('tango.core.ThreadPool'),
      M('tango.core.Time'),
      M('tango.core.Traits'),
      M('tango.core.Tuple'),
      M('tango.core.Vararg'),
      M('tango.core.Variant'),
      M('tango.core.Version'),
    ]),
    P('tango.io',[
      P('tango.io.device',[
        M('tango.io.device.Array'),
        M('tango.io.device.BitBucket'),
        M('tango.io.device.Conduit'),
        M('tango.io.device.Device'),
        M('tango.io.device.File'),
        M('tango.io.device.FileMap'),
        M('tango.io.device.SerialPort'),
        M('tango.io.device.TempFile'),
        M('tango.io.device.ThreadPipe'),
      ]),
      P('tango.io.model',[
        M('tango.io.model.IConduit'),
        M('tango.io.model.IFile'),
      ]),
      P('tango.io.selector',[
        P('tango.io.selector.model',[
          M('tango.io.selector.model.ISelector'),
        ]),
        M('tango.io.selector.AbstractSelector'),
        M('tango.io.selector.EpollSelector'),
        M('tango.io.selector.PollSelector'),
        M('tango.io.selector.SelectSelector'),
        M('tango.io.selector.Selector'),
        M('tango.io.selector.SelectorException'),
      ]),
      P('tango.io.stream',[
        M('tango.io.stream.Buffered'),
        M('tango.io.stream.Bzip'),
        M('tango.io.stream.Data'),
        M('tango.io.stream.DataFile'),
        M('tango.io.stream.Delimiters'),
        M('tango.io.stream.Digester'),
        M('tango.io.stream.Endian'),
        M('tango.io.stream.Format'),
        M('tango.io.stream.Greedy'),
        M('tango.io.stream.Iterator'),
        M('tango.io.stream.Lines'),
        M('tango.io.stream.Map'),
        M('tango.io.stream.Patterns'),
        M('tango.io.stream.Quotes'),
        M('tango.io.stream.Snoop'),
        M('tango.io.stream.Text'),
        M('tango.io.stream.TextFile'),
        M('tango.io.stream.Typed'),
        M('tango.io.stream.Utf'),
        M('tango.io.stream.Zlib'),
      ]),
      P('tango.io.vfs',[
        P('tango.io.vfs.model',[
          M('tango.io.vfs.model.Vfs'),
        ]),
        M('tango.io.vfs.FileFolder'),
        M('tango.io.vfs.FtpFolder'),
        M('tango.io.vfs.LinkedFolder'),
        M('tango.io.vfs.VirtualFolder'),
        M('tango.io.vfs.ZipFolder'),
      ]),
      M('tango.io.Console'),
      M('tango.io.FilePath'),
      M('tango.io.FileScan'),
      M('tango.io.FileSystem'),
      M('tango.io.Path'),
      M('tango.io.Stdout'),
      M('tango.io.UnicodeFile'),
    ]),
    P('tango.math',[
      P('tango.math.random',[
        P('tango.math.random.engines',[
          M('tango.math.random.engines.ArraySource'),
          M('tango.math.random.engines.CMWC'),
          M('tango.math.random.engines.KISS'),
          M('tango.math.random.engines.KissCmwc'),
          M('tango.math.random.engines.Sync'),
          M('tango.math.random.engines.Twister'),
          M('tango.math.random.engines.URandom'),
        ]),
        M('tango.math.random.ExpSource'),
        M('tango.math.random.Kiss'),
        M('tango.math.random.NormalSource'),
        M('tango.math.random.Random'),
        M('tango.math.random.Twister'),
        M('tango.math.random.Ziggurat'),
      ]),
      M('tango.math.Bessel'),
      M('tango.math.BigInt'),
      M('tango.math.Bracket'),
      M('tango.math.Elliptic'),
      M('tango.math.ErrorFunction'),
      M('tango.math.GammaFunction'),
      M('tango.math.IEEE'),
      M('tango.math.Math'),
      M('tango.math.Probability'),
    ]),
    P('tango.net',[
      P('tango.net.device',[
        M('tango.net.device.Berkeley'),
        M('tango.net.device.Datagram'),
        M('tango.net.device.LocalSocket'),
        M('tango.net.device.Multicast'),
        M('tango.net.device.SSLSocket'),
        M('tango.net.device.Socket'),
      ]),
      P('tango.net.ftp',[
        M('tango.net.ftp.FtpClient'),
        M('tango.net.ftp.Telnet'),
      ]),
      P('tango.net.http',[
        P('tango.net.http.model',[
          M('tango.net.http.model.HttpParamsView'),
        ]),
        M('tango.net.http.ChunkStream'),
        M('tango.net.http.HttpClient'),
        M('tango.net.http.HttpConst'),
        M('tango.net.http.HttpCookies'),
        M('tango.net.http.HttpGet'),
        M('tango.net.http.HttpHeaders'),
        M('tango.net.http.HttpParams'),
        M('tango.net.http.HttpPost'),
        M('tango.net.http.HttpStack'),
        M('tango.net.http.HttpTokens'),
        M('tango.net.http.HttpTriplet'),
      ]),
      P('tango.net.model',[
        M('tango.net.model.UriView'),
      ]),
      P('tango.net.util',[
        P('tango.net.util.c',[
          M('tango.net.util.c.OpenSSL'),
        ]),
        M('tango.net.util.MemCache'),
        M('tango.net.util.PKI'),
      ]),
      M('tango.net.InternetAddress'),
      M('tango.net.Uri'),
    ]),
    P('tango.stdc',[
      P('tango.stdc.posix',[
        P('tango.stdc.posix.arpa',[
          M('tango.stdc.posix.arpa.inet'),
        ]),
        P('tango.stdc.posix.net',[
          M('tango.stdc.posix.net.if_'),
        ]),
        P('tango.stdc.posix.netinet',[
          M('tango.stdc.posix.netinet.in_'),
          M('tango.stdc.posix.netinet.tcp'),
        ]),
        P('tango.stdc.posix.sys',[
          M('tango.stdc.posix.sys.ipc'),
          M('tango.stdc.posix.sys.mman'),
          M('tango.stdc.posix.sys.select'),
          M('tango.stdc.posix.sys.shm'),
          M('tango.stdc.posix.sys.socket'),
          M('tango.stdc.posix.sys.stat'),
          M('tango.stdc.posix.sys.statvfs'),
          M('tango.stdc.posix.sys.time'),
          M('tango.stdc.posix.sys.types'),
          M('tango.stdc.posix.sys.uio'),
          M('tango.stdc.posix.sys.utsname'),
          M('tango.stdc.posix.sys.wait'),
        ]),
        M('tango.stdc.posix.config'),
        M('tango.stdc.posix.dirent'),
        M('tango.stdc.posix.dlfcn'),
        M('tango.stdc.posix.fcntl'),
        M('tango.stdc.posix.grp'),
        M('tango.stdc.posix.inttypes'),
        M('tango.stdc.posix.langinfo'),
        M('tango.stdc.posix.poll'),
        M('tango.stdc.posix.pthread'),
        M('tango.stdc.posix.pwd'),
        M('tango.stdc.posix.sched'),
        M('tango.stdc.posix.semaphore'),
        M('tango.stdc.posix.setjmp'),
        M('tango.stdc.posix.signal'),
        M('tango.stdc.posix.stdio'),
        M('tango.stdc.posix.stdlib'),
        M('tango.stdc.posix.termios'),
        M('tango.stdc.posix.time'),
        M('tango.stdc.posix.ucontext'),
        M('tango.stdc.posix.unistd'),
        M('tango.stdc.posix.utime'),
      ]),
      M('tango.stdc.complex'),
      M('tango.stdc.config'),
      M('tango.stdc.ctype'),
      M('tango.stdc.errno'),
      M('tango.stdc.fenv'),
      M('tango.stdc.inttypes'),
      M('tango.stdc.limits'),
      M('tango.stdc.locale'),
      M('tango.stdc.math'),
      M('tango.stdc.signal'),
      M('tango.stdc.stdarg'),
      M('tango.stdc.stddef'),
      M('tango.stdc.stdint'),
      M('tango.stdc.stdio'),
      M('tango.stdc.stdlib'),
      M('tango.stdc.string'),
      M('tango.stdc.stringz'),
      M('tango.stdc.tgmath'),
      M('tango.stdc.time'),
      M('tango.stdc.wctype'),
    ]),
    P('tango.sys',[
      P('tango.sys.consts',[
        M('tango.sys.consts.errno'),
        M('tango.sys.consts.fcntl'),
        M('tango.sys.consts.socket'),
        M('tango.sys.consts.sysctl'),
        M('tango.sys.consts.unistd'),
      ]),
      P('tango.sys.darwin',[
        P('tango.sys.darwin.consts',[
          M('tango.sys.darwin.consts.errno'),
          M('tango.sys.darwin.consts.fcntl'),
          M('tango.sys.darwin.consts.machine'),
          M('tango.sys.darwin.consts.socket'),
          M('tango.sys.darwin.consts.sysctl'),
          M('tango.sys.darwin.consts.unistd'),
        ]),
        M('tango.sys.darwin.darwin'),
      ]),
      P('tango.sys.freebsd',[
        P('tango.sys.freebsd.consts',[
          M('tango.sys.freebsd.consts.errno'),
          M('tango.sys.freebsd.consts.fcntl'),
          M('tango.sys.freebsd.consts.socket'),
          M('tango.sys.freebsd.consts.sysctl'),
          M('tango.sys.freebsd.consts.unistd'),
        ]),
        M('tango.sys.freebsd.freebsd'),
      ]),
      P('tango.sys.linux',[
        P('tango.sys.linux.consts',[
          M('tango.sys.linux.consts.errno'),
          M('tango.sys.linux.consts.fcntl'),
          M('tango.sys.linux.consts.socket'),
          M('tango.sys.linux.consts.sysctl'),
          M('tango.sys.linux.consts.unistd'),
        ]),
        M('tango.sys.linux.epoll'),
        M('tango.sys.linux.inotify'),
        M('tango.sys.linux.linux'),
        M('tango.sys.linux.tipc'),
      ]),
      P('tango.sys.solaris',[
        P('tango.sys.solaris.consts',[
          M('tango.sys.solaris.consts.errno'),
          M('tango.sys.solaris.consts.fcntl'),
          M('tango.sys.solaris.consts.socket'),
          M('tango.sys.solaris.consts.sysctl'),
          M('tango.sys.solaris.consts.unistd'),
        ]),
        M('tango.sys.solaris.solaris'),
      ]),
      P('tango.sys.win32',[
        P('tango.sys.win32.consts',[
          M('tango.sys.win32.consts.errno'),
          M('tango.sys.win32.consts.fcntl'),
          M('tango.sys.win32.consts.socket'),
          M('tango.sys.win32.consts.sysctl'),
          M('tango.sys.win32.consts.unistd'),
        ]),
        M('tango.sys.win32.CodePage'),
        M('tango.sys.win32.IUnknown'),
        M('tango.sys.win32.Macros'),
        M('tango.sys.win32.Process'),
        M('tango.sys.win32.SpecialPath'),
        M('tango.sys.win32.Types'),
        M('tango.sys.win32.UserGdi'),
        M('tango.sys.win32.WsaSock'),
      ]),
      M('tango.sys.Common'),
      M('tango.sys.Environment'),
      M('tango.sys.HomeFolder'),
      M('tango.sys.Pipe'),
      M('tango.sys.Process'),
      M('tango.sys.SharedLib'),
    ]),
    P('tango.text',[
      P('tango.text.convert',[
        M('tango.text.convert.DateTime'),
        M('tango.text.convert.Float'),
        M('tango.text.convert.Format'),
        M('tango.text.convert.Integer'),
        M('tango.text.convert.Layout'),
        M('tango.text.convert.TimeStamp'),
        M('tango.text.convert.UnicodeBom'),
        M('tango.text.convert.Utf'),
      ]),
      P('tango.text.json',[
        M('tango.text.json.Json'),
        M('tango.text.json.JsonEscape'),
        M('tango.text.json.JsonParser'),
      ]),
      P('tango.text.locale',[
        M('tango.text.locale.Collation'),
        M('tango.text.locale.Convert'),
        M('tango.text.locale.Core'),
        M('tango.text.locale.Data'),
        M('tango.text.locale.Locale'),
        M('tango.text.locale.Parse'),
        M('tango.text.locale.Posix'),
        M('tango.text.locale.Win32'),
      ]),
      P('tango.text.xml',[
        M('tango.text.xml.DocEntity'),
        M('tango.text.xml.DocPrinter'),
        M('tango.text.xml.DocTester'),
        M('tango.text.xml.Document'),
        M('tango.text.xml.PullParser'),
        M('tango.text.xml.SaxParser'),
      ]),
      M('tango.text.Arguments'),
      M('tango.text.Ascii'),
      M('tango.text.Regex'),
      M('tango.text.Search'),
      M('tango.text.Text'),
      M('tango.text.Unicode'),
      M('tango.text.UnicodeData'),
      M('tango.text.Util'),
    ]),
    P('tango.time',[
      P('tango.time.chrono',[
        M('tango.time.chrono.Calendar'),
        M('tango.time.chrono.Gregorian'),
        M('tango.time.chrono.GregorianBased'),
        M('tango.time.chrono.Hebrew'),
        M('tango.time.chrono.Hijri'),
        M('tango.time.chrono.Japanese'),
        M('tango.time.chrono.Korean'),
        M('tango.time.chrono.Taiwan'),
        M('tango.time.chrono.ThaiBuddhist'),
      ]),
      M('tango.time.Clock'),
      M('tango.time.ISO8601'),
      M('tango.time.StopWatch'),
      M('tango.time.Time'),
      M('tango.time.WallClock'),
    ]),
    P('tango.util',[
      P('tango.util.cipher',[
        M('tango.util.cipher.AES'),
        M('tango.util.cipher.Blowfish'),
        M('tango.util.cipher.ChaCha'),
        M('tango.util.cipher.Cipher'),
        M('tango.util.cipher.RC4'),
        M('tango.util.cipher.RC6'),
        M('tango.util.cipher.Salsa20'),
        M('tango.util.cipher.TEA'),
        M('tango.util.cipher.XTEA'),
      ]),
      P('tango.util.compress',[
        P('tango.util.compress.c',[
          M('tango.util.compress.c.bzlib'),
          M('tango.util.compress.c.zlib'),
        ]),
        M('tango.util.compress.Zip'),
      ]),
      P('tango.util.container',[
        P('tango.util.container.model',[
          M('tango.util.container.model.IContainer'),
        ]),
        P('tango.util.container.more',[
          M('tango.util.container.more.BitSet'),
          M('tango.util.container.more.CacheMap'),
          M('tango.util.container.more.HashFile'),
          M('tango.util.container.more.Heap'),
          M('tango.util.container.more.Stack'),
          M('tango.util.container.more.StackMap'),
          M('tango.util.container.more.Vector'),
        ]),
        M('tango.util.container.CircularList'),
        M('tango.util.container.Clink'),
        M('tango.util.container.Container'),
        M('tango.util.container.HashMap'),
        M('tango.util.container.HashSet'),
        M('tango.util.container.LinkedList'),
        M('tango.util.container.RedBlack'),
        M('tango.util.container.Slink'),
        M('tango.util.container.SortedMap'),
      ]),
      P('tango.util.digest',[
        M('tango.util.digest.Crc32'),
        M('tango.util.digest.Digest'),
        M('tango.util.digest.Md2'),
        M('tango.util.digest.Md4'),
        M('tango.util.digest.Md5'),
        M('tango.util.digest.MerkleDamgard'),
        M('tango.util.digest.Ripemd128'),
        M('tango.util.digest.Ripemd160'),
        M('tango.util.digest.Ripemd256'),
        M('tango.util.digest.Ripemd320'),
        M('tango.util.digest.Sha0'),
        M('tango.util.digest.Sha01'),
        M('tango.util.digest.Sha1'),
        M('tango.util.digest.Sha256'),
        M('tango.util.digest.Sha512'),
        M('tango.util.digest.Tiger'),
        M('tango.util.digest.Whirlpool'),
      ]),
      P('tango.util.encode',[
        M('tango.util.encode.Base16'),
        M('tango.util.encode.Base32'),
        M('tango.util.encode.Base64'),
      ]),
      P('tango.util.log',[
        P('tango.util.log.model',[
          M('tango.util.log.model.ILogger'),
        ]),
        M('tango.util.log.AppendConsole'),
        M('tango.util.log.AppendFile'),
        M('tango.util.log.AppendFiles'),
        M('tango.util.log.AppendMail'),
        M('tango.util.log.AppendSocket'),
        M('tango.util.log.AppendSyslog'),
        M('tango.util.log.Config'),
        M('tango.util.log.ConfigProps'),
        M('tango.util.log.LayoutChainsaw'),
        M('tango.util.log.LayoutDate'),
        M('tango.util.log.Log'),
        M('tango.util.log.Trace'),
      ]),
      P('tango.util.uuid',[
        M('tango.util.uuid.NamespaceGenV3'),
        M('tango.util.uuid.NamespaceGenV5'),
        M('tango.util.uuid.RandomGen'),
        M('tango.util.uuid.Uuid'),
      ]),
      M('tango.util.Convert'),
      M('tango.util.MinMax'),
    ]),
  ]),
])
);

var g_creationTime = 1345532233;
